Repository jekyll/jekyll-admin, pull requests merged in 2020-03, with the labels that each got.

#565 Allow selecting static files in MarkdownEditor
  src/components/MarkdownEditor.js
  src/components/tests/__snapshots__/markdowneditor.spec.js.snap
  src/components/tests/markdowneditor.spec.js
Labels: enhancement, front-end

#389 Initialize a new advanced metadata field for tags
  src/components/metadata/MetaButtons.js
  src/components/metadata/MetaField.js
  src/components/metadata/MetaObject.js
  src/components/metadata/MetaSimple.js
  src/components/metadata/MetaTags.js
  src/components/metadata/tests/metasimple.spec.js
  src/components/metadata/tests/metatags.spec.js
  src/containers/MetaFields.js
  src/styles/metafields.scss
Labels: front-end

#586 Release :gem: v0.10.0
  README.md
  lib/jekyll-admin/version.rb
  package.json
  screenshot.png
Labels: release

#573 Integrate react-scripts
  .babelrc
  .env
  .eslintrc.json
  bundlesize.config.json
  config-overrides.js
  package.json
  public/favicon.ico
  public/index.html
  script/build
  src/components/Button.js
  src/components/FilePreview.js
  src/components/metadata/MetaButtons.js
  src/components/metadata/MetaTags.js
  src/containers/Header.js
  src/containers/tests/__snapshots__/header.spec.js.snap
  src/containers/views/NotFound.js
  src/ducks/action_tests/collections.spec.js
  src/ducks/action_tests/datafiles.spec.js
  src/ducks/action_tests/drafts.spec.js
  src/ducks/action_tests/pages.spec.js
  src/ducks/action_tests/staticfiles.spec.js
  src/index.html
  src/index.js
  src/setupTests.js
  src/styles/vendors/font-awesome/_variables.scss
  tools/build.js
  tools/buildHtml.js
  tools/chalkConfig.js
  tools/srcServer.js
  tools/startMessage.js
  tools/testCi.js
  webpack.config.dev.js
  webpack.config.prod.js
  yarn.lock
Labels: front-end

#589 Allow searching without enter key press
  src/components/form/InputSearch.js
Labels: ux

#590 Fix listing static files in index view
  src/components/FilePreview.js
Labels: fix
